### ISSUE TITLE
[1.16.5] [Request] Modded Structure compat 

### ISSUE THREAD

**Issue by TelepathicGrunt** [MeinKraft/Crimson-Compass#5]
Hello! I am the developer of Repurposed Structures. Someone asked me about your mod and said it does not have a compass for any of my structures. A dynamic compass that can be set by the user to find any modded structure might be something that you want to look into. The structure registry has all the modded structures in it so the compass could grab the structure from there in order to search the world for it. 

Just something that could be nice to have!

**Comment by MeinKraft** [comment]
I was planning on adding a single compass which would allow the user to scroll through and select a structure to find

Thing is, Im extremely new to java and forge, and have been focusing on other projects.  Its a great idea, if I can wrap my head around it
