### ISSUE TITLE
Crafting recipe?

### ISSUE THREAD

**Issue by BastardNeko** [MeinKraft/Crimson-Compass#6]
Is there a crafting recipe for the structure compass's? JEI isn't showing anything :/

**Comment by MeinKraft** [comment]
nope

although I should be adding some soon

you can use datapacks to set them yourself if so inclined

**Comment by MeinKraft** [comment]
1.16.5 recipes are done and released on CurseForge
1.17.1 recipes are done. Need to implement the village changes, somehow
